# Generated by Django 5.1.4 on 2025-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_question_explication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='browser',
            field=models.TextField(blank=True, null=True),
        ),
    ]
